// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBELcbaq73dXi3EMGbmiN54ZJgvTeeyFNc',
    appId: '1:984361496021:web:24e4556559cd56254ce15c',
    messagingSenderId: '984361496021',
    projectId: 'matrimony-f956a',
    authDomain: 'matrimony-f956a.firebaseapp.com',
    storageBucket: 'matrimony-f956a.firebasestorage.app',
    measurementId: 'G-SQF35SFXBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIOUqAJoQmUTrZezlSAfDOKsiu5u7tJHs',
    appId: '1:984361496021:android:29cef9aa56be7bbc4ce15c',
    messagingSenderId: '984361496021',
    projectId: 'matrimony-f956a',
    storageBucket: 'matrimony-f956a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBELcbaq73dXi3EMGbmiN54ZJgvTeeyFNc',
    appId: '1:984361496021:web:66f33d60b02ede0f4ce15c',
    messagingSenderId: '984361496021',
    projectId: 'matrimony-f956a',
    authDomain: 'matrimony-f956a.firebaseapp.com',
    storageBucket: 'matrimony-f956a.firebasestorage.app',
    measurementId: 'G-932B56PR3G',
  );
}
